import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import DiveLogList from "@/components/templates/divLogList";
import DiveLogForm from "@/components/templates/diveLogForm";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { DiveLog } from "@/domains/diveLog";

export default function New() {
  const router = useRouter();
  const { register, handleSubmit } = useForm<DiveLog>();
  const onSubmit = async (data: DiveLog) => {
    await fetch(`${process.env.NEXT_PUBLIC_HOST}/api/diveLogs`, {
      method: "PUT",
      body: JSON.stringify(data),
    });
    router.push("/");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DiveLogForm
          register={register}
          addNewDiveLog={handleSubmit(onSubmit)}
        />
      </main>
    </>
  );
}
