import BuddyCommentForm from "@/components/templates/BuddyCommentForm";
import { ShareDiveLog } from "@/pages/api/share/diveLogs/[uuid]";
import { BuddyComment } from "@/schemas/buudy";
import styles from "@/styles/Home.module.css";
import { ResponseError } from "@/utils/type";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { useState } from "react";
import { z } from "zod";

type Props = {
  diveLog: ShareDiveLog;
  uuid: string;
  buddyId: number;
  buddyName: string;
};

function BuddyComment(props: Props) {
  const { diveLog: initDivelog, uuid, buddyId, buddyName } = props;

  const [diveLog, setDiveLog] = useState(initDivelog);
  const [error, setError] = useState<ResponseError>();

  const handleSubmit = async (data: BuddyComment) => {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/share/diveLogs/${uuid}/buddies/${buddyId}/comments/new`,
      {
        method: "POST",
        body: JSON.stringify({ ...data }),
      }
    );
    if (!res.ok) {
      setError(await res.json());
      return;
    }

    // 自分や他ユーザーが追加したコメントを表示できるようにコメントを再取得する
    // コメントのポストに失敗しても他ユーザーがコメントしている可能性がある
    const resDiveLog = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/share/diveLogs/${uuid}`
    );
    if (!resDiveLog.ok) {
      setError(await res.json());
      return;
    }
    const diveLog = (await resDiveLog.json()) as ShareDiveLog;
    setDiveLog(diveLog);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BuddyCommentForm
          diveLog={diveLog}
          onSubmit={handleSubmit}
          error={error}
          commenter={buddyName}
        />
      </main>
    </>
  );
}

const querySchema = z.object({
  uuid: z.string(),
  buddyId: z.coerce.number(),
  buddyName: z.string(),
});

export async function getServerSideProps(context: GetServerSidePropsContext) {
  // /shere/${uuid}/commentsに直接URL指定した場合は名前を指定してないので名前入力画面にリダイレクトする
  const parse = querySchema.safeParse(context.query);
  if (!parse.success) {
    return {
      redirect: {
        destination: `/share/diveLogs/${context.query.uuid}`,
        permanent: false,
      },
    };
  }

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL}/api/share/diveLogs/${parse.data.uuid}`
  );
  if (!res.ok) {
    // TODO: エラーページに遷移させた方がいい
    return {
      redirect: {
        destination: `/share/diveLogs/${context.query.uuid}`,
        permanent: false,
      },
    };
  }

  const diveLog = (await res.json()) as ShareDiveLog;
  console.log(diveLog);
  return { props: { diveLog, ...parse.data } };
}

export default BuddyComment;
