import Head from "next/head";
import styles from "@/styles/Home.module.css";
import DiveLogForm from "@/components/templates/DiveLogForm";
import { useRouter } from "next/router";
import { DiveLog } from "@/schemas/diveLog";
import { useUser } from "@supabase/auth-helpers-react";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { GetServerSidePropsContext } from "next";

type Props = {
  diveLog: DiveLog;
};

function Exist(props: Props) {
  const { diveLog } = props;

  const user = useUser();
  const router = useRouter();

  const onSubmit = async (data: DiveLog) => {
    if (!user) {
      return await router.replace("/");
    }
    await fetch(
      `${process.env.NEXT_PUBLIC_HOST}/api/users/${user.id}/diveLogs/${router.query.id}`,
      {
        method: "PUT",
        body: JSON.stringify(data),
      }
    );
    router.push("/diveLogs");
  };

  const onDelete = async () => {
    if (!user) {
      return await router.replace("/");
    }
    await fetch(
      `${process.env.NEXT_PUBLIC_HOST}/api/users/${user.id}/diveLogs/${router.query.id}`,
      {
        method: "DELETE",
      }
    );
    router.push("/diveLogs");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DiveLogForm
          diveLog={diveLog}
          onSubmit={onSubmit}
          onBack={() => router.push("/diveLogs")}
          onDelete={onDelete}
        />
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const supabaseServerClient = createServerSupabaseClient(context);
  const {
    data: { user },
  } = await supabaseServerClient.auth.getUser();

  if (!user) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_HOST}/api/users/${user.id}/diveLogs/${context.query.id}`
  );
  const diveLog = (await res.json()) as DiveLog;
  return { props: { diveLog } };
}

export default Exist;
