import Head from "next/head";
import styles from "@/styles/Home.module.css";
import DiveLogForm from "@/components/templates/DiveLogForm";
import { useRouter } from "next/router";
import { DiveLog } from "@/schemas/diveLog";

type Props = {
  diveLog: DiveLog;
};

function Exist(props: Props) {
  const { diveLog } = props;

  const router = useRouter();
  const onSubmit = async (data: DiveLog) => {
    await fetch(
      `${process.env.NEXT_PUBLIC_HOST}/api/diveLogs/${router.query.id}`,
      {
        method: "PUT",
        body: JSON.stringify(data),
      }
    );
    router.push("/diveLogs");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DiveLogForm diveLog={diveLog} onSubmit={onSubmit} />
      </main>
    </>
  );
}

// TODO: context の型って何？
export async function getServerSideProps(context: any) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_HOST}/api/diveLogs/${context.query.id}`
  );
  const diveLog = (await res.json()) as DiveLog;
  return { props: { diveLog } };
}

export default Exist;
