import DiveLogForm from "@/components/templates/DiveLogForm";
import { DiveLog } from "@/schemas/diveLog";
import styles from "@/styles/Home.module.css";
import { useUser } from "@supabase/auth-helpers-react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function New() {
  const router = useRouter();
  const user = useUser();
  const handleSubmit = async (data: DiveLog) => {
    if (!user) {
      return await router.replace("/");
    }
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/users/${user.id}/diveLogs`,
      {
        method: "POST",
        body: JSON.stringify({ ...data }),
      }
    );
    if (res.ok) {
      router.push("/diveLogs");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DiveLogForm
          onSubmit={handleSubmit}
          onBack={() => router.push("/diveLogs")}
        />
      </main>
    </>
  );
}
