import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { Stack } from "@mui/material";
import { Auth } from "@supabase/auth-ui-react";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { ThemeSupa } from "@supabase/auth-ui-shared";

export default function Home() {
  const router = useRouter();
  const supabaseClient = useSupabaseClient();
  const user = useUser();

  if (user) {
    router.push("/diveLogs");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Stack>
          <Auth
            redirectTo="http://localhost:3000/diveLogs"
            appearance={{ theme: ThemeSupa }}
            supabaseClient={supabaseClient}
            providers={["google", "github"]}
            socialLayout="horizontal"
          />
        </Stack>
      </main>
    </>
  );
}
