import Head from "next/head";
import styles from "@/styles/Home.module.css";
import DiveLogList from "@/components/templates/divLogList";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { CircularProgress, Stack, TextField, Button } from "@mui/material";

export default function Home() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // if (error) {
  //   return (
  //     <main className={styles.main}>
  //       <p>Error: {error.message}</p>
  //     </main>
  //   );
  // }
  // if (loading) {
  //   return (
  //     <main className={styles.main}>
  //       <CircularProgress />
  //     </main>
  //   );
  // }
  // if () {
  //   router.push("/diveLogs");
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Stack spacing={2}>
          <TextField label="メールアドレス" variant="outlined" />
          <TextField label="パスワード" variant="outlined" />
          <Button variant="contained" onClick={() => {}}>
            ログイン
          </Button>
          <Button variant="contained" onClick={() => {}}>
            新規作成
          </Button>
        </Stack>
      </main>
    </>
  );
}
